eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**


server:
  port: '8060'

management:
  tracing:
    sampling:
      probability: '1.0'



