eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: employee-service
server:
  port: '8082'

management:
  tracing:
    sampling:
      probability: '1.0'

